name: 'Issue Comment'
on:
  issues:
    types: [opened]

env:
  tf_working_dir: './'

jobs:
  destroy-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.comment.body }}
        id: comment
      - name: Checkout
        uses: actions/checkout@v2
        if: steps.comment.outputs.stdout == 'yes'
