name: 'Issue Comment'
on:
  issues:
    types: [opened]

env:
  tf_working_dir: './'

jobs:
  destroy-plan:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
