name: 'Pull Request'
on:
  pull_request:
env:
  tf_working_dir: ./test
jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Steps Context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - name: parse
        id: parse
        run: |
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
          if (( ${#files[@]} > 1 )); then
              echo "more than one file"
              exit 0
          fi
          count=0
          for i in ${files[@]}; do
            files[$count]="${i%/*}"
            count=$((count + 1))
          done
          echo "::set-output name=change_directory::${files[@]}"
    outputs:
      change_directory: ${{ steps.parse.outputs.change_directory }}
  second-job:
    name: Second Job
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.first-job.outputs.change_directory }}
